# Data Parameters
patch_length: 16
stride: 8
num_channels: 3
lookback_window: 1024
num_batches: 128


loss: cross_entropy

# Training Parameters
epochs: 75

# Optimizer Parameters
optimizer: 'adamw'
lr: .0003
weight_decay: .01
min_lr: .000001
scheduler: 'cosine_restart'

# Transformer Encoder Parameters
d_model : 128
t_heads: 16
t_dim_feedforward: 256
t_dropout: 0.2
t_activation: 'gelu'
t_num_layers: 3

# MLP Parameters
mlp_hidden_size: 128
num_classes: 10

# Channel Independence Parameters
channel_independence: true

# Evaluation Parameters
hook_attention_maps: false

output_dir: config_4_adamw_cosine_restarts/